#配置spring 包含了连接和模版的映射
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/0830work
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    mode: HTML
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/


#定义了日志的输出
logging:
  level:
    cn.kgc: debug
#定义的端口的设置
server:
  port: 8090
  servlet:
    context-path: /0830work


#定义了Mybatis的控制模式  映射mapper文件和使用囫囵大小写的形式
mybatis-plus:

  # 实体类包路径
  type-aliases-package: cn.kgc.entity

  # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

  # mapper XML文件位置
  mapper-locations:
    - classpath:mapper/*.xml

  # 打开自动驼峰命名映射
  configuration:
    map-underscore-to-camel-case: true