spring:
  datasource:
    url: jdbc:mysql://localhost:3306/0831work
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

logging:
  level:
    cn.kgc: debug

#总结: yml的编辑包括数据库源,渲染模版的页面路径,日志输出,端口和服务器路径的映射,数据库操作的约定,使用逻辑删除和mapper配置文件的路径映射,包别名规划,映射时候的驼峰和下划线转化格式
#总结: YML文件配置包括[^数据库源配置]、[^Thymeleaf模板相关设定]、[^日志级别定义]、[^服务器端口与Context路径映射]、[^MyBatis-Plus全局配置]如[逻辑删除]、[^Mapper文件位置]、[^类型别名指定]及[^命名格式转换设置]

server:
  port: 8090
  servlet:
    context-path: /0831work

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  #逻辑删除对应的字段的值
      logic-not-delete-value: 0
      logic-delete-value: 1
      table-underline: false #取消他的下划线
  mapper-locations:
    - classpath:mapper/user/*.xml
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: cn.kgc.entity,cn.kgc.user.entity